### ISSUE TITLE
Top layer travel Z-Hop

### ISSUE THREAD

**Issue by duisenberg** [MatterHackers/MatterSlice#145]
When printing the final top layer, travel moves run in build height, leaving travel marks on the model surface. For some reason - I run retraction with Z Lift - this doesnt seem to apply here.

**Comment by larsbrubaker** [comment]
Can you export your profile and attach it to this issue. I will investigate either way but that might help.

**Comment by larsbrubaker** [comment]
I am definitely seeing z-hop in the top layer of my test prints. If you can add your settings, the exported gcode and possibly the part as a zip to this issue, that would be a big help. I think the issue your having is probably due to the Minimum Travel Requiring Retraction. Setting this to a much smaller number will likely get you the result you are looking for.

![2016-11-28 12_18_13-matterhackers_ mattercontrol 1 6](https://cloud.githubusercontent.com/assets/1158332/20684458/dca38bec-b564-11e6-8973-403ae1fb4485.png)

**Comment by duisenberg** [comment]
Might be my settings lead to issues:
![image2](https://cloud.githubusercontent.com/assets/21085153/20686773/47c2d5f4-b5ba-11e6-8c76-0b9a10cb2c74.jpg)

Atm a bit short in time, will try to catch it on image tomorrow.

**Comment by duisenberg** [comment]
Found an image that shows the issue, the red marked travel was about 20mm distance. Also there are marks on top but they are very close to 8mm so minimum travel should have matched here.

![mc-scr](https://cloud.githubusercontent.com/assets/21085153/20687594/6565f26e-b5bd-11e6-8c5c-f87f8d473089.jpg)

**Comment by duisenberg** [comment]
Here some more samples:
![img_1770](https://cloud.githubusercontent.com/assets/21085153/20767794/e08e22d4-b73b-11e6-812a-642d99d4a267.jpg)
![img_1774](https://cloud.githubusercontent.com/assets/21085153/20767798/e55a6eb2-b73b-11e6-9a70-28baec340e9d.jpg)
![img_1776](https://cloud.githubusercontent.com/assets/21085153/20767821/f8a97f08-b73b-11e6-8207-30b722f3932c.jpg)

Print settings same as above. 
Most travels do correctly lead to retraction with Z hop but some are omitted. Didnt see it happen with infill layers, only bottom and top layers. Not a so big issue, but since the Matterslicer really works well on surfaces it would be even better if it wouldnt leave a travel scar.
Using the 1.6.07828 btw. Profile is attached.

[Profile.txt](https://github.com/MatterHackers/MatterSlice/files/622817/Profile.txt)

**Comment by duisenberg** [comment]
As for 1.6.1.7967 I didnt see the issue happen any more on top layers.
