### ISSUE TITLE
Skirt goes around nonexistant wipe tower

### ISSUE THREAD

**Issue by unlimitedbacon** [MatterHackers/MatterSlice#68]
When the Wipe Tower Size > 0, the skirt goes around where the wipe tower would be even though the wipe tower doesn't exist because only one material is being printed.

![nowipetower](https://cloud.githubusercontent.com/assets/3131268/16504725/60a2ab5c-3ece-11e6-98c8-0dca756b7e6c.png)

**Comment by jlewin** [comment]
Due to the way the wipe tower is processed, and when the skirt is generated, the skirt code has no knowledge of whether or not the wipe tower will exist (it's conditional based on the presence of one or more material switches and the conditional determination occurs long after the skirt is generated). The skirt code only knows if wipe polygons exist and if so, it includes them in the convex hull calculation. 

We've talked about a number of workarounds to resolve this issue, including having the skirt ignore the wipe tower and operate only on the part polygons or modifying the execution order so that the skirt could be determine if the tower is to be generated. To date, both routes have negative trade offs and the user workaround is to clear the wipe tower field when no material switches exist, thus nullifying the invalid behavior.
